[project]
name = "obsidian2anki"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "ruff>=0.12.1",
]
